import { useEffect, useMemo, useState } from "react";
import { Archive, Bell, CalendarClock, ChevronDown, CircleHelp, ClipboardList, CreditCard, Gauge, Gift, LayoutDashboard, LifeBuoy, Menu, MoreHorizontal, Package, PanelLeftClose, Plus, ReceiptText, Settings, ShieldCheck, Ticket, Users, Wallet, X } from "lucide-react";
import { useClientAuth } from "@/contexts/client-auth";
import { api, type ClientPayer, type ClientPayment, type ClientTeamMember, type ClientVisit, type PublicTariff, type PublicTariffCategory, type WdttClientCategoryItem, type WdttClientSlotItem } from "@/lib/api";
import { Button, Checkbox, EmptyState, FormField, IconButton, Input, Modal, Select, StatusBadge, Stepper, Switcher, Textarea } from "@/components/astracat/dragon";
import "./astracat-billing.css";

type PageId = "home" | "profile" | "roles" | "payers" | "referrals" | "cart" | "orders" | "methods" | "discounts" | "preferences" | "subscriptions" | "olcrtc" | "payments" | "expenses" | "renewals" | "usage" | "tickets" | "archive" | "statistics" | "visits" | "help";
type ModalName = "topup" | "ticket" | "order" | "olcrtcOrder" | "payer" | "member" | null;
type SubscriptionRow = { id: string; service: string; plan: string; status: string; expiresAt: string | null; days: number | null; traffic: string; devices: string; autoRenew: boolean; type: "root" | "secondary" };
type TicketRow = { id: string; subject: string; status: string; createdAt: string; updatedAt: string };

const groups: { label?: string; items: Array<{ id: PageId; label: string; icon: typeof LayoutDashboard }> }[] = [
  { items: [{ id: "home", label: "Главная", icon: LayoutDashboard }] },
  { label: "Клиент", items: [{ id: "profile", label: "Профиль", icon: Users }, { id: "roles", label: "Роли пользователей", icon: ShieldCheck }, { id: "payers", label: "Плательщики", icon: Users }, { id: "referrals", label: "Реферальная программа", icon: Gift }, { id: "cart", label: "Корзина", icon: ReceiptText }, { id: "orders", label: "Заказы", icon: ClipboardList }, { id: "methods", label: "Способы оплаты", icon: CreditCard }, { id: "discounts", label: "Скидки", icon: Gift }, { id: "preferences", label: "Настройки пользователя", icon: Settings }] },
  { label: "Товары / Услуги", items: [{ id: "subscriptions", label: "Подписки ASTRACAT", icon: Package }, { id: "olcrtc", label: "OlcRTC", icon: Gauge }] },
  { label: "Финансы", items: [{ id: "payments", label: "Платежи", icon: Wallet }, { id: "expenses", label: "Расходы", icon: ReceiptText }, { id: "renewals", label: "Автопродление услуг", icon: CalendarClock }, { id: "usage", label: "Потребление ресурсов", icon: Gauge }] },
  { label: "Поддержка", items: [{ id: "tickets", label: "Запросы", icon: Ticket }, { id: "archive", label: "Архив запросов", icon: Archive }] },
  { label: "Инструменты", items: [{ id: "statistics", label: "Статистика", icon: Gauge }, { id: "visits", label: "Журнал посещений", icon: ClipboardList }] },
  { items: [{ id: "help", label: "Справка", icon: CircleHelp }] },
];
const labels = Object.fromEntries(groups.flatMap((group) => group.items.map((item) => [item.id, item.label]))) as Record<PageId, string>;

function parseSubscription(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object") return {};
  const raw = value as Record<string, unknown>;
  if (raw.response && typeof raw.response === "object") return raw.response as Record<string, unknown>;
  if (raw.data && typeof raw.data === "object" && (raw.data as Record<string, unknown>).response && typeof (raw.data as Record<string, unknown>).response === "object") return (raw.data as Record<string, unknown>).response as Record<string, unknown>;
  return raw;
}
function numberValue(value: unknown): number | null { const n = typeof value === "number" ? value : typeof value === "string" ? Number(value) : NaN; return Number.isFinite(n) ? n : null; }
function bytes(value: number | null) { if (value == null) return "—"; if (value >= 1024 ** 3) return `${(value / 1024 ** 3).toFixed(1)} ГБ`; if (value >= 1024 ** 2) return `${(value / 1024 ** 2).toFixed(1)} МБ`; return `${Math.round(value / 1024)} КБ`; }
function date(value: string | null) { return value ? new Date(value).toLocaleDateString("ru-RU") : "—"; }
function money(value: number, currency: string) { return new Intl.NumberFormat("ru-RU", { style: "currency", currency: currency.toUpperCase() === "RUB" ? "RUB" : currency.toUpperCase() === "EUR" ? "EUR" : "USD", maximumFractionDigits: 2 }).format(value); }
function daysUntil(value: string | null) { if (!value) return null; const result = Math.ceil((new Date(value).getTime() - Date.now()) / 86400000); return Number.isFinite(result) ? Math.max(0, result) : null; }

function useBillingData(token: string | null) {
  const [state, setState] = useState<{ loading: boolean; error: string | null; profile: Awaited<ReturnType<typeof api.clientMe>> | null; subscriptions: SubscriptionRow[]; payments: ClientPayment[]; tickets: TicketRow[]; devices: number; tariffs: PublicTariff[]; tariffCategories: PublicTariffCategory[]; olcrtcCategories: WdttClientCategoryItem[]; olcrtcSlots: WdttClientSlotItem[]; referrals: { total: number; earned: number } | null; payers: ClientPayer[]; members: ClientTeamMember[]; visits: ClientVisit[] }>({ loading: true, error: null, profile: null, subscriptions: [], payments: [], tickets: [], devices: 0, tariffs: [], tariffCategories: [], olcrtcCategories: [], olcrtcSlots: [], referrals: null, payers: [], members: [], visits: [] });
  const reload = async () => {
    if (!token) return;
    setState((previous) => ({ ...previous, loading: true, error: null }));
    try {
      const [profile, subscriptionsRes, paymentsRes, ticketsRes, devicesRes, tariffsRes, referralsRes, payersRes, membersRes, visitsRes, olcrtcTariffsRes, olcrtcSlotsRes] = await Promise.all([api.clientMe(token), api.clientAllSubscriptions(token), api.clientPayments(token), api.getTickets(token).catch(() => ({ items: [] })), api.getMyAllDevices(token).catch(() => ({ total: 0, items: [] })), api.getPublicTariffs(), api.getClientReferralStats(token).catch(() => null), api.getClientPayers(token).catch(() => ({ items: [] })), api.getClientTeamMembers(token).catch(() => ({ items: [] })), api.getClientVisits(token).catch(() => ({ items: [] })), api.getWdttClientTariffs(token).catch(() => ({ items: [] })), api.getWdttSlots(token).catch(() => ({ items: [] }))]);
      const subscriptions = subscriptionsRes.items.map((item): SubscriptionRow => {
        const raw = parseSubscription(item.subscription); const traffic = raw.userTraffic && typeof raw.userTraffic === "object" ? raw.userTraffic as Record<string, unknown> : {};
        const expiresAt = typeof raw.expireAt === "string" ? raw.expireAt : null; const limit = numberValue(raw.trafficLimitBytes); const used = numberValue(traffic.usedTrafficBytes ?? raw.trafficUsed);
        return { id: item.id, service: item.type === "root" ? "VPN-подписка" : `Дополнительная подписка №${item.subscriptionIndex ?? "—"}`, plan: item.tariffDisplayName || "Без тарифа", status: typeof raw.status === "string" ? raw.status : "PENDING", expiresAt, days: daysUntil(expiresAt), traffic: limit == null || limit <= 0 ? "Безлимит" : `${bytes(used)} / ${bytes(limit)}`, devices: `${numberValue(raw.hwidDeviceLimit) ?? "—"}`, autoRenew: Boolean(item.autoRenewEnabled), type: item.type };
      });
      const referral = referralsRes as { referrals?: unknown[]; totalEarned?: number; totalEarnings?: number } | null;
      setState({ loading: false, error: null, profile, subscriptions, payments: paymentsRes.items, tickets: ticketsRes.items, devices: devicesRes.total, tariffs: tariffsRes.items.flatMap((group) => group.tariffs), tariffCategories: tariffsRes.items, olcrtcCategories: olcrtcTariffsRes.items, olcrtcSlots: olcrtcSlotsRes.items, referrals: referral ? { total: referral.referrals?.length ?? 0, earned: numberValue(referral.totalEarned ?? referral.totalEarnings) ?? 0 } : null, payers: payersRes.items, members: membersRes.items, visits: visitsRes.items });
    } catch (error) { setState((previous) => ({ ...previous, loading: false, error: error instanceof Error ? error.message : "Не удалось загрузить данные" })); }
  };
  useEffect(() => { void reload(); }, [token]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (token) void api.recordClientVisit(token).catch(() => {}); }, [token]);
  return { ...state, reload };
}

function savedTabs(): PageId[] { try { const value = JSON.parse(localStorage.getItem("astracat-tabs-client") ?? "[]") as PageId[]; return value.filter((id) => id in labels).length ? value.filter((id) => id in labels) : ["home"]; } catch { return ["home"]; } }

export function AstracatBillingPage() {
  const { state: auth, refreshProfile, logout } = useClientAuth(); const data = useBillingData(auth.token);
  const [theme, setTheme] = useState<"light" | "dark">("light"); const [collapsed, setCollapsed] = useState(false); const [tabs, setTabs] = useState<PageId[]>(savedTabs); const [active, setActive] = useState<PageId>(() => savedTabs()[0]); const [modal, setModal] = useState<ModalName>(null); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { localStorage.setItem("astracat-tabs-client", JSON.stringify(tabs)); }, [tabs]);
  const open = (id: PageId) => { setTabs((current) => current.includes(id) ? current : [...current, id]); setActive(id); };
  const close = (id: PageId) => setTabs((current) => { const next = current.filter((value) => value !== id); if (id === active) setActive(next[next.length - 1] ?? "home"); return next.length ? next : ["home"]; });
  const inform = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 4000); };
  if (!auth.token) return <main className="astracat"><section className="ac-page"><EmptyState title="Требуется вход" text="Войдите в клиентский кабинет, чтобы открыть биллинг." action={<Button onClick={() => { window.location.href = "/cabinet/login"; }}>Войти</Button>} /></section></main>;
  if (data.loading && !data.profile) return <main className="astracat"><section className="ac-page"><EmptyState title="Загрузка кабинета" text="Получаем данные из ASTRACAT API." /></section></main>;
  return <main className={`astracat ${theme === "dark" ? "astracat--dark" : ""} ${collapsed ? "astracat--collapsed" : ""}`}>
    <header className="ac-top-header"><button className="ac-brand" onClick={() => open("home")} aria-label="ASTRACAT Billing: главная"><span>✦</span> ASTRACAT <small>BILLING</small></button><div className="ac-top-actions"><button className="ac-balance" onClick={() => setModal("topup")}>Баланс: <strong>{money(data.profile?.balance ?? 0, data.profile?.preferredCurrency ?? "USD")}</strong><span>Пополнить</span></button><IconButton label="Уведомления"><Bell size={18} /><b>{data.tickets.filter((ticket) => ticket.status === "open").length}</b></IconButton><button className="ac-user" onClick={() => void logout()}>{data.profile?.email ?? data.profile?.telegramUsername ?? "Клиент"}<ChevronDown size={15} /></button></div></header>
    <div className="ac-sub-header"><IconButton label="Свернуть меню" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <Menu size={18} /> : <PanelLeftClose size={18} />}</IconButton><span>Клиентский кабинет</span><div><button onClick={() => setTheme(theme === "light" ? "dark" : "light")}>{theme === "light" ? "Тёмная тема" : "Светлая тема"}</button><button onClick={() => void data.reload()}>Обновить</button></div></div>
    <aside className="ac-sidebar" aria-label="Основная навигация"><nav>{groups.map((group, index) => <section key={`${group.label ?? "root"}-${index}`} className="ac-sidebar-group">{group.label && <h2>{group.label}</h2>}{group.items.map((item) => <button key={item.id} className={active === item.id ? "is-active" : ""} onClick={() => open(item.id)} title={collapsed ? item.label : undefined}><item.icon size={17} /><span>{item.label}</span></button>)}</section>)}</nav><footer><CircleHelp size={16} /><span>Справка и поддержка</span></footer></aside>
    <section className="ac-workspace"><nav className="ac-tabbar" aria-label="Открытые разделы">{tabs.map((tab) => <button key={tab} className={active === tab ? "is-active" : ""} onClick={() => setActive(tab)}><span>{labels[tab]}</span>{tab !== "home" && <X size={14} onClick={(event) => { event.stopPropagation(); close(tab); }} aria-label={`Закрыть ${labels[tab]}`} />}</button>)}<button className="ac-tab-more" onClick={() => setTabs([active])} title="Закрыть остальные вкладки"><MoreHorizontal size={18} /></button></nav>{notice && <div className="ac-toast" role="status">{notice}</div>}{data.error && <div className="ac-toast" role="alert">{data.error}</div>}<BillingPage page={active} data={data} token={auth.token} open={open} modal={setModal} inform={inform} refreshProfile={refreshProfile} /></section>
    {modal && <BillingModal name={modal} token={auth.token} tariffCategories={data.tariffCategories} olcrtcCategories={data.olcrtcCategories} close={() => setModal(null)} inform={inform} reload={data.reload} />}
  </main>;
}

function Frame({ title, description, actions, children }: { title: string; description?: string; actions?: React.ReactNode; children: React.ReactNode }) { return <article className="ac-page"><header className="ac-page-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="ac-page-actions">{actions}</div>}</header>{children}</article>; }
function BillingPage({ page, data, token, open, modal, inform, refreshProfile }: { page: PageId; data: ReturnType<typeof useBillingData>; token: string; open: (page: PageId) => void; modal: (name: ModalName) => void; inform: (message: string) => void; refreshProfile: () => Promise<void> }) {
  if (page === "home") return <Dashboard data={data} open={open} modal={modal} />;
  if (page === "subscriptions") return <Subscriptions data={data} token={token} modal={modal} reload={data.reload} inform={inform} />;
  if (page === "payments" || page === "orders") return <Payments payments={data.payments} order={page === "orders"} modal={modal} />;
  if (page === "tickets" || page === "archive") return <Tickets tickets={data.tickets.filter((ticket) => page === "archive" ? ticket.status === "closed" : ticket.status !== "closed")} modal={modal} />;
  if (page === "profile") return <Profile token={token} profile={data.profile} refresh={refreshProfile} inform={inform} />;
  if (page === "payers") return <Payers payers={data.payers} token={token} modal={modal} reload={data.reload} inform={inform} />;
  if (page === "roles") return <TeamMembers members={data.members} token={token} modal={modal} reload={data.reload} inform={inform} />;
  if (page === "visits") return <Visits visits={data.visits} />;
  if (page === "discounts") return <Discounts token={token} profile={data.profile} inform={inform} />;
  if (page === "olcrtc") return <OlcRtc categories={data.olcrtcCategories} slots={data.olcrtcSlots} token={token} modal={modal} reload={data.reload} inform={inform} />;
  if (page === "renewals") return <Renewals data={data} token={token} reload={data.reload} inform={inform} />;
  if (page === "usage") return <Usage data={data} />;
  if (page === "referrals") return <Frame title="Реферальная программа"><section className="ac-widget-grid"><Widget title="Приглашено" icon={<Users size={18} />}><strong className="ac-money">{data.referrals?.total ?? 0}</strong></Widget><Widget title="Доход" icon={<Gift size={18} />}><strong className="ac-money">{money(data.referrals?.earned ?? 0, data.profile?.preferredCurrency ?? "USD")}</strong></Widget></section></Frame>;
  if (page === "methods") return <Frame title="Способы оплаты"><EmptyState title={data.profile?.yookassaPaymentMethodTitle ? data.profile.yookassaPaymentMethodTitle : "Сохранённых способов оплаты нет"} text="Сохранённый способ появляется после успешного платежа через подключённый шлюз." /></Frame>;
  if (page === "cart") return <Frame title="Корзина"><EmptyState title="Корзина пуста" text="Заказ создаётся через мастер услуги и фиксируется в существующем журнале платежей." action={<Button onClick={() => modal("order")}><Plus size={16} /> Заказать услугу</Button>} /></Frame>;
  if (page === "statistics") return <Frame title="Статистика"><section className="ac-widget-grid"><Widget title="Подписки" icon={<Package size={18} />}><strong className="ac-money">{data.subscriptions.length}</strong></Widget><Widget title="Платежи" icon={<Wallet size={18} />}><strong className="ac-money">{data.payments.length}</strong></Widget></section></Frame>;
  if (page === "preferences") return <Preferences />;
  return <Frame title={labels[page]}><EmptyState title="Нет данных" text="Этот раздел не содержит отдельных сущностей в текущей модели сервиса; демонстрационные записи не показываются." /></Frame>;
}

function Widget({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="ac-widget"><header><h2>{icon}{title}</h2></header>{children}</section>; }
function Dashboard({ data, open, modal }: { data: ReturnType<typeof useBillingData>; open: (page: PageId) => void; modal: (name: ModalName) => void }) { const first = data.subscriptions[0]; const last = data.payments[0]; return <Frame title="Главная" description="Актуальные данные вашего аккаунта" actions={<Button onClick={() => modal("order")}><Plus size={16} /> Заказать услугу</Button>}><section className="ac-quick-actions"><h2>Быстрый доступ</h2><button onClick={() => modal("order")}><Package /> Заказать VPN</button><button onClick={() => modal("topup")}><Wallet /> Пополнить баланс</button><button onClick={() => modal("ticket")}><LifeBuoy /> Задать вопрос</button><button onClick={() => open("profile")}><Settings /> Настройки</button></section><section className="ac-widget-grid"><Widget title="Мой баланс" icon={<Wallet size={18} />}><strong className="ac-money">{money(data.profile?.balance ?? 0, data.profile?.preferredCurrency ?? "USD")}</strong></Widget><Widget title="Активные услуги" icon={<Package size={18} />}>{first ? <><div className="ac-widget-line"><span>{first.plan}</span><StatusBadge tone={first.status === "ACTIVE" ? "success" : "warning"}>{first.status}</StatusBadge></div><p>до {date(first.expiresAt)} · {first.days ?? "—"} дней</p></> : <p>Активных услуг нет</p>}</Widget><Widget title="Последний платёж" icon={<ReceiptText size={18} />}>{last ? <><strong>{money(last.amount, last.currency)}</strong><p>{date(last.paidAt ?? last.createdAt)} · {last.status}</p></> : <p>Платежей пока нет</p>}</Widget><Widget title="Обращения" icon={<LifeBuoy size={18} />}><strong className="ac-money">{data.tickets.filter((ticket) => ticket.status !== "closed").length}</strong><p>Открытых запросов</p></Widget></section></Frame>; }
function Subscriptions({ data, token, modal, reload, inform }: { data: ReturnType<typeof useBillingData>; token: string; modal: (name: ModalName) => void; reload: () => Promise<void>; inform: (message: string) => void }) { const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string[]>([]); const rows = useMemo(() => data.subscriptions.filter((row) => `${row.service} ${row.plan}`.toLowerCase().includes(query.toLowerCase())), [data.subscriptions, query]); const toggleRenew = async () => { const row = data.subscriptions.find((item) => item.id === selected[0]); if (!row) return; try { await api.clientUpdateAutoRenew(token, { enabled: !row.autoRenew }); await reload(); inform("Настройка автопродления сохранена"); } catch (error) { inform(error instanceof Error ? error.message : "Не удалось изменить автопродление"); } }; return <Frame title="Подписки ASTRACAT" description="Данные загружаются из провижининга и базы подписок" actions={<Button onClick={() => modal("order")}><Plus size={16} /> Заказать услугу</Button>}><section className="ac-toolbar"><div><Button tone="secondary" disabled={selected.length !== 1} onClick={toggleRenew}>Автопродление</Button></div><Input aria-label="Поиск подписок" placeholder="Поиск" value={query} onChange={(event) => setQuery(event.target.value)} /></section><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th><Checkbox aria-label="Выбрать все" checked={rows.length > 0 && selected.length === rows.length} onChange={() => setSelected(selected.length === rows.length ? [] : rows.map((row) => row.id))} /></th><th>Услуга</th><th>Тариф</th><th>Статус</th><th>Окончание</th><th>Дней</th><th>Потребление</th><th>Устройства</th><th>Авто</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className={selected.includes(row.id) ? "is-selected" : ""}><td><Checkbox aria-label={`Выбрать ${row.plan}`} checked={selected.includes(row.id)} onChange={() => setSelected((current) => current.includes(row.id) ? current.filter((id) => id !== row.id) : [...current, row.id])} /></td><td>{row.service}</td><td>{row.plan}</td><td><StatusBadge tone={row.status === "ACTIVE" ? "success" : "warning"}>{row.status}</StatusBadge></td><td>{date(row.expiresAt)}</td><td>{row.days ?? "—"}</td><td>{row.traffic}</td><td>{row.devices}</td><td>{row.autoRenew ? "Включено" : "Выключено"}</td></tr>)}</tbody></table></div>{rows.length === 0 && <EmptyState title="Подписок нет" text="Оформите услугу, чтобы она появилась здесь после оплаты." />}</Frame>; }
function Payments({ payments, order, modal }: { payments: ClientPayment[]; order: boolean; modal: (name: ModalName) => void }) { return <Frame title={order ? "Заказы" : "Платежи"} actions={order ? <Button onClick={() => modal("order")}><Plus size={16} /> Заказать услугу</Button> : <Button onClick={() => modal("topup")}><Plus size={16} /> Пополнить</Button>}><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>Номер</th><th>Сумма</th><th>Статус</th><th>Создан</th><th>Оплачен</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>{order ? payment.orderId : payment.id}</td><td>{money(payment.amount, payment.currency)}</td><td><StatusBadge tone={payment.status === "PAID" ? "success" : "warning"}>{payment.status}</StatusBadge></td><td>{date(payment.createdAt)}</td><td>{date(payment.paidAt)}</td></tr>)}</tbody></table></div>{payments.length === 0 && <EmptyState title="Записей нет" text="После создания платежа запись появится в этом журнале." />}</Frame>; }
function Tickets({ tickets, modal }: { tickets: TicketRow[]; modal: (name: ModalName) => void }) { return <Frame title="Запросы" actions={<Button onClick={() => modal("ticket")}><Plus size={16} /> Создать запрос</Button>}><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>Тема</th><th>Статус</th><th>Обновлён</th></tr></thead><tbody>{tickets.map((ticket) => <tr key={ticket.id}><td>{ticket.subject}</td><td><StatusBadge tone={ticket.status === "closed" ? "neutral" : "success"}>{ticket.status}</StatusBadge></td><td>{date(ticket.updatedAt)}</td></tr>)}</tbody></table></div>{tickets.length === 0 && <EmptyState title="Обращений нет" text="Создайте запрос — он будет сохранён в системе поддержки." />}</Frame>; }
function Payers({ payers, token, modal, reload, inform }: { payers: ClientPayer[]; token: string; modal: (name: ModalName) => void; reload: () => Promise<void>; inform: (message: string) => void }) { const run = async (work: () => Promise<unknown>, success: string) => { try { await work(); await reload(); inform(success); } catch (error) { inform(error instanceof Error ? error.message : "Операция не выполнена"); } }; return <Frame title="Плательщики" description="Реквизиты хранятся в вашем аккаунте и доступны для оформления услуг." actions={<Button onClick={() => modal("payer")}><Plus size={16} /> Добавить плательщика</Button>}><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>Наименование</th><th>Тип</th><th>Страна</th><th>ИНН / Tax ID</th><th>По умолчанию</th><th></th></tr></thead><tbody>{payers.map((payer) => <tr key={payer.id}><td><strong>{payer.name}</strong><br /><small>{payer.email ?? payer.address ?? "—"}</small></td><td>{payer.type === "COMPANY" ? "Компания" : "Физлицо"}</td><td>{payer.country}</td><td>{payer.taxId ?? "—"}</td><td>{payer.isDefault ? <StatusBadge tone="success">Основной</StatusBadge> : <Button tone="secondary" onClick={() => void run(() => api.updateClientPayer(token, payer.id, { isDefault: true }), "Основной плательщик обновлён")}>Сделать основным</Button>}</td><td><Button tone="secondary" onClick={() => { if (window.confirm(`Удалить плательщика «${payer.name}»?`)) void run(() => api.deleteClientPayer(token, payer.id), "Плательщик удалён"); }}>Удалить</Button></td></tr>)}</tbody></table></div>{payers.length === 0 && <EmptyState title="Плательщиков пока нет" text="Добавьте физлицо или компанию — запись будет сохранена в базе ASTRACAT." action={<Button onClick={() => modal("payer")}><Plus size={16} /> Добавить</Button>} />}</Frame>; }
function TeamMembers({ members, token, modal, reload, inform }: { members: ClientTeamMember[]; token: string; modal: (name: ModalName) => void; reload: () => Promise<void>; inform: (message: string) => void }) { const roleLabels: Record<ClientTeamMember["role"], string> = { VIEWER: "Просмотр", BILLING: "Биллинг", SUPPORT: "Поддержка", ADMIN: "Администратор" }; const run = async (work: () => Promise<unknown>, success: string) => { try { await work(); await reload(); inform(success); } catch (error) { inform(error instanceof Error ? error.message : "Операция не выполнена"); } }; return <Frame title="Роли пользователей" description="Контакты и назначенные роли дополнительных пользователей вашего аккаунта." actions={<Button onClick={() => modal("member")}><Plus size={16} /> Добавить пользователя</Button>}><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>Пользователь</th><th>Роль</th><th>Статус</th><th>Добавлен</th><th></th></tr></thead><tbody>{members.map((member) => <tr key={member.id}><td><strong>{member.name}</strong><br /><small>{member.email}</small></td><td><Select value={member.role} onChange={(event) => void run(() => api.updateClientTeamMember(token, member.id, { role: event.target.value as ClientTeamMember["role"] }), "Роль обновлена")}>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></td><td><Button tone="secondary" onClick={() => void run(() => api.updateClientTeamMember(token, member.id, { isActive: !member.isActive }), member.isActive ? "Пользователь отключён" : "Пользователь включён")}>{member.isActive ? "Активен" : "Отключён"}</Button></td><td>{date(member.createdAt)}</td><td><Button tone="secondary" onClick={() => { if (window.confirm(`Удалить пользователя «${member.email}»?`)) void run(() => api.deleteClientTeamMember(token, member.id), "Пользователь удалён"); }}>Удалить</Button></td></tr>)}</tbody></table></div>{members.length === 0 && <EmptyState title="Дополнительных пользователей нет" text="Добавьте пользователя и назначьте ему роль для ведения клиентского аккаунта." action={<Button onClick={() => modal("member")}><Plus size={16} /> Добавить</Button>} />}</Frame>; }
function Visits({ visits }: { visits: ClientVisit[] }) { return <Frame title="Журнал посещений" description="Записи создаёт сервер при входе и открытии клиентского кабинета."><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>Дата и время</th><th>Способ</th><th>IP-адрес</th><th>Устройство</th></tr></thead><tbody>{visits.map((visit) => <tr key={visit.id}><td>{new Date(visit.createdAt).toLocaleString("ru-RU")}</td><td>{visit.authMethod}</td><td>{visit.ip ?? "—"}</td><td title={visit.userAgent ?? undefined}>{visit.userAgent ?? "—"}</td></tr>)}</tbody></table></div>{visits.length === 0 && <EmptyState title="Посещений ещё нет" text="После первой авторизации здесь появится защищённая серверная запись." />}</Frame>; }
function Discounts({ token, profile, inform }: { token: string; profile: Awaited<ReturnType<typeof api.clientMe>> | null; inform: (message: string) => void }) { const [code, setCode] = useState(""); const [result, setResult] = useState<{ type: string; discountPercent?: number | null; discountFixed?: number | null; durationDays?: number | null; name: string } | null>(null); const [error, setError] = useState<string | null>(null); const check = async () => { try { setError(null); setResult(await api.clientCheckPromoCode(token, code.trim())); } catch (reason) { setResult(null); setError(reason instanceof Error ? reason.message : "Не удалось проверить промокод"); } }; const activate = async () => { try { const response = await api.clientActivatePromoCode(token, code.trim()); inform(response.message); setResult(null); setCode(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось активировать промокод"); } }; return <Frame title="Скидки и промокоды" description="Проверка и применение выполняются существующим серверным сервисом промокодов."><section className="ac-widget-grid"><Widget title="Персональная скидка" icon={<Gift size={18} />}><strong className="ac-money">{profile?.personalDiscountPercent ? `${profile.personalDiscountPercent}%` : "Нет"}</strong><p>{profile?.personalDiscountPercent ? "Учтётся сервером при оплате услуги." : "Администратор ещё не назначал персональную скидку."}</p></Widget><Widget title="Промокод" icon={<ReceiptText size={18} />}><div className="ac-widget-line"><Input placeholder="Введите код" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} /><Button disabled={!code.trim()} onClick={() => void check()}>Проверить</Button></div>{error && <p className="text-destructive">{error}</p>}{result && <p>{result.type === "DISCOUNT" ? `${result.name}: ${result.discountPercent ? `${result.discountPercent}%` : money(result.discountFixed ?? 0, profile?.preferredCurrency ?? "RUB")}` : `${result.name}: ${result.durationDays} дней`}</p>}{result?.type === "FREE_DAYS" && <Button onClick={() => void activate()}>Активировать дни</Button>}{result?.type === "DISCOUNT" && <p className="ac-hint">Введите этот код в мастере заказа — сервер применит скидку при создании платежа.</p>}</Widget></section></Frame>; }
function OlcRtc({ categories, slots, token, modal, reload, inform }: { categories: WdttClientCategoryItem[]; slots: WdttClientSlotItem[]; token: string; modal: (name: ModalName) => void; reload: () => Promise<void>; inform: (message: string) => void }) { const run = async (work: () => Promise<unknown>, success: string) => { try { await work(); await reload(); inform(success); } catch (error) { inform(error instanceof Error ? error.message : "Операция не выполнена"); } }; const configure = (slot: WdttClientSlotItem) => { const provider = window.prompt("Провайдер комнаты: telemost или wbstream", "telemost"); if (provider !== "telemost" && provider !== "wbstream") return; const roomId = window.prompt("Ссылка или ID комнаты"); if (!roomId?.trim()) return; void run(() => api.configureWdttSlot(token, slot.id, { provider, roomId: roomId.trim() }), "OlcRTC подключение настроено"); }; return <Frame title="OlcRTC" description="Покупка, выдача и настройка персональных OlcRTC-подключений через существующие API." actions={<Button onClick={() => modal("olcrtcOrder")}><Plus size={16} /> Купить OlcRTC</Button>}><section className="ac-widget-grid">{categories.map((category) => <Widget key={category.id} title={category.name} icon={<Gauge size={18} />}>{category.tariffs.map((tariff) => <div className="ac-widget-line" key={tariff.id}><span>{tariff.name} · {tariff.durationDays} дней</span><strong>{money(tariff.price, tariff.currency)}</strong></div>)}{category.tariffs.length === 0 && <p>Нет доступных тарифов</p>}</Widget>)}</section><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>Нода</th><th>Статус</th><th>Окончание</th><th>Ссылка</th><th></th></tr></thead><tbody>{slots.map((slot) => <tr key={slot.id}><td>{slot.nodeName}</td><td><StatusBadge tone={slot.status === "ACTIVE" ? "success" : "warning"}>{slot.status}</StatusBadge></td><td>{date(slot.expiresAt)}</td><td><Input value={slot.wdttLink} readOnly /></td><td>{slot.requiresConfiguration ? <Button tone="secondary" onClick={() => configure(slot)}>Настроить</Button> : <Button tone="secondary" onClick={() => void run(() => api.reissueWdttSlot(token, slot.id), "Ссылка OlcRTC перевыпущена")}>Перевыпустить</Button>}</td></tr>)}</tbody></table></div>{slots.length === 0 && <EmptyState title="OlcRTC-подключений нет" text="Выберите тариф — после успешной оплаты сервер автоматически создаст подключение." action={<Button onClick={() => modal("olcrtcOrder")}>Выбрать тариф</Button>} />}</Frame>; }
function Profile({ token, profile, refresh, inform }: { token: string; profile: Awaited<ReturnType<typeof api.clientMe>> | null; refresh: () => Promise<void>; inform: (message: string) => void }) { const [language, setLanguage] = useState(profile?.preferredLang ?? "ru"); const [currency, setCurrency] = useState(profile?.preferredCurrency ?? "USD"); const [autoRenew, setAutoRenew] = useState(Boolean(profile?.autoRenewEnabled)); const save = async () => { try { await api.clientUpdateProfile(token, { preferredLang: language, preferredCurrency: currency }); await refresh(); inform("Профиль сохранён"); } catch (error) { inform(error instanceof Error ? error.message : "Не удалось сохранить профиль"); } }; const changeRenew = async (enabled: boolean) => { try { await api.clientUpdateAutoRenew(token, { enabled }); setAutoRenew(enabled); inform("Настройка автопродления сохранена"); } catch (error) { inform(error instanceof Error ? error.message : "Не удалось сохранить настройку"); } }; return <Frame title="Профиль" actions={<Button onClick={() => void save()}>Сохранить</Button>}><section className="ac-form-grid"><FormField label="Email"><Input value={profile?.email ?? ""} disabled /></FormField><FormField label="Telegram"><Input value={profile?.telegramUsername ?? profile?.telegramId ?? "Не привязан"} disabled /></FormField><FormField label="Язык"><Select value={language} onChange={(event) => setLanguage(event.target.value)}><option value="ru">Русский</option><option value="en">English</option></Select></FormField><FormField label="Валюта"><Select value={currency} onChange={(event) => setCurrency(event.target.value)}><option value="RUB">RUB</option><option value="USD">USD</option><option value="EUR">EUR</option></Select></FormField></section><section className="ac-security"><h2>Безопасность и продление</h2><Switcher label="Автопродление услуг" checked={autoRenew} onChange={(value) => void changeRenew(value)} /><Button tone="secondary" onClick={() => { window.location.href = "/cabinet/profile"; }}>Сменить пароль и 2FA</Button></section></Frame>; }
function Renewals({ data, token, reload, inform }: { data: ReturnType<typeof useBillingData>; token: string; reload: () => Promise<void>; inform: (message: string) => void }) { const enabled = Boolean(data.profile?.autoRenewEnabled); return <Frame title="Автопродление услуг"><section className="ac-widget-grid"><Widget title="Статус" icon={<CalendarClock size={18} />}><StatusBadge tone={enabled ? "success" : "neutral"}>{enabled ? "Включено" : "Выключено"}</StatusBadge><p>{data.profile?.autoRenewPromoCode ? `Промокод: ${data.profile.autoRenewPromoCode}` : "Промокод не выбран"}</p></Widget><Widget title="Активные подписки" icon={<Package size={18} />}><strong className="ac-money">{data.subscriptions.length}</strong></Widget></section><Button className="mt-3" onClick={async () => { try { await api.clientUpdateAutoRenew(token, { enabled: !enabled }); await reload(); inform("Автопродление обновлено"); } catch (error) { inform(error instanceof Error ? error.message : "Не удалось обновить настройку"); } }}>{enabled ? "Отключить" : "Включить"}</Button></Frame>; }
function Usage({ data }: { data: ReturnType<typeof useBillingData> }) { return <Frame title="Потребление ресурсов"><div className="ac-table-wrap"><table className="ac-table"><thead><tr><th>Подписка</th><th>Тариф</th><th>Трафик</th><th>Устройства</th></tr></thead><tbody>{data.subscriptions.map((row) => <tr key={row.id}><td>{row.service}</td><td>{row.plan}</td><td>{row.traffic}</td><td>{row.devices}</td></tr>)}</tbody></table></div><p className="ac-hint">Всего зарегистрированных устройств: {data.devices}</p></Frame>; }
function Preferences() { const [rows, setRows] = useState(localStorage.getItem("astracat-rows") ?? "25"); return <Frame title="Настройки пользователя"><section className="ac-form-grid"><FormField label="Строк на странице"><Select value={rows} onChange={(event) => { setRows(event.target.value); localStorage.setItem("astracat-rows", event.target.value); }}><option value="25">25</option><option value="50">50</option></Select></FormField></section><p className="ac-hint">Параметры интерфейса хранятся только на этом устройстве.</p></Frame>; }
function BillingModal({ name, token, tariffCategories, olcrtcCategories, close, inform, reload }: { name: Exclude<ModalName, null>; token: string; tariffCategories: PublicTariffCategory[]; olcrtcCategories: WdttClientCategoryItem[]; close: () => void; inform: (message: string) => void; reload: () => Promise<void> }) { const [amount, setAmount] = useState(""); const [subject, setSubject] = useState(""); const [message, setMessage] = useState(""); const [payerName, setPayerName] = useState(""); const [payerCountry, setPayerCountry] = useState("RU"); const [payerType, setPayerType] = useState<ClientPayer["type"]>("PERSON"); const [payerTaxId, setPayerTaxId] = useState(""); const [payerEmail, setPayerEmail] = useState(""); const [payerAddress, setPayerAddress] = useState(""); const [memberName, setMemberName] = useState(""); const [memberEmail, setMemberEmail] = useState(""); const [memberRole, setMemberRole] = useState<ClientTeamMember["role"]>("VIEWER"); const [error, setError] = useState<string | null>(null); const submit = async (work: () => Promise<void>) => { try { setError(null); await work(); await reload(); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Операция не выполнена"); } };
  if (name === "payer") return <Modal title="Новый плательщик" onClose={close}><div className="ac-modal-body"><section className="ac-form-grid"><FormField label="Тип"><Select value={payerType} onChange={(event) => setPayerType(event.target.value as ClientPayer["type"])}><option value="PERSON">Физическое лицо</option><option value="COMPANY">Компания</option></Select></FormField><FormField label="Страна (ISO-2)"><Input maxLength={2} value={payerCountry} onChange={(event) => setPayerCountry(event.target.value.toUpperCase())} /></FormField><FormField label={payerType === "COMPANY" ? "Название компании" : "ФИО"}><Input value={payerName} onChange={(event) => setPayerName(event.target.value)} /></FormField><FormField label="ИНН / Tax ID"><Input value={payerTaxId} onChange={(event) => setPayerTaxId(event.target.value)} /></FormField><FormField label="Email"><Input type="email" value={payerEmail} onChange={(event) => setPayerEmail(event.target.value)} /></FormField><FormField label="Адрес"><Input value={payerAddress} onChange={(event) => setPayerAddress(event.target.value)} /></FormField></section>{error && <p className="text-destructive">{error}</p>}<div className="ac-modal-actions"><Button tone="secondary" onClick={close}>Отмена</Button><Button disabled={!payerName.trim() || payerCountry.length !== 2} onClick={() => void submit(async () => { await api.createClientPayer(token, { type: payerType, country: payerCountry, name: payerName.trim(), taxId: payerTaxId.trim() || null, email: payerEmail.trim() || null, address: payerAddress.trim() || null, isDefault: false }); inform("Плательщик добавлен"); })}>Сохранить</Button></div></div></Modal>;
  if (name === "member") return <Modal title="Новый пользователь" onClose={close}><div className="ac-modal-body"><section className="ac-form-grid"><FormField label="Имя"><Input value={memberName} onChange={(event) => setMemberName(event.target.value)} /></FormField><FormField label="Email"><Input type="email" value={memberEmail} onChange={(event) => setMemberEmail(event.target.value)} /></FormField><FormField label="Роль"><Select value={memberRole} onChange={(event) => setMemberRole(event.target.value as ClientTeamMember["role"])}><option value="VIEWER">Просмотр</option><option value="BILLING">Биллинг</option><option value="SUPPORT">Поддержка</option><option value="ADMIN">Администратор</option></Select></FormField></section><p className="ac-hint">Роль и контакт будут сохранены в клиентском аккаунте.</p>{error && <p className="text-destructive">{error}</p>}<div className="ac-modal-actions"><Button tone="secondary" onClick={close}>Отмена</Button><Button disabled={!memberName.trim() || !memberEmail.trim()} onClick={() => void submit(async () => { await api.createClientTeamMember(token, { name: memberName.trim(), email: memberEmail.trim(), role: memberRole, isActive: true }); inform("Пользователь добавлен"); })}>Сохранить</Button></div></div></Modal>;
  if (name === "topup") return <Modal title="Пополнение баланса" onClose={close}><div className="ac-modal-body"><FormField label="Сумма"><Input type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} /></FormField><p className="ac-hint">Будет создан реальный платёж через подключённый ЮKassa.</p>{error && <p className="text-destructive">{error}</p>}<div className="ac-modal-actions"><Button tone="secondary" onClick={close}>Отмена</Button><Button disabled={!Number(amount)} onClick={() => void submit(async () => { const payment = await api.yookassaCreatePayment(token, { amount: Number(amount), currency: "RUB" }); inform("Переход к оплате"); window.location.assign(payment.confirmationUrl); })}>Продолжить</Button></div></div></Modal>;
  if (name === "ticket") return <Modal title="Новое обращение" onClose={close}><div className="ac-modal-body"><FormField label="Тема"><Input value={subject} onChange={(event) => setSubject(event.target.value)} /></FormField><FormField label="Сообщение"><Textarea rows={5} value={message} onChange={(event) => setMessage(event.target.value)} /></FormField>{error && <p className="text-destructive">{error}</p>}<div className="ac-modal-actions"><Button tone="secondary" onClick={close}>Отмена</Button><Button disabled={!subject.trim() || !message.trim()} onClick={() => void submit(async () => { await api.createTicket(token, { subject: subject.trim(), message: message.trim() }); inform("Обращение создано"); })}>Отправить</Button></div></div></Modal>;
  return <OrderModal token={token} tariffCategories={tariffCategories} olcrtcCategories={olcrtcCategories} initialProduct={name === "olcrtcOrder" ? "olcrtc" : "vpn"} close={close} reload={reload} inform={inform} />;
}

type CheckoutMethod = "balance" | "yookassa" | "yoomoney" | "cryptopay" | "heleket" | "lava" | "freekassa" | "overpay" | "platega";
type CheckoutProduct = "vpn" | "olcrtc";
const checkoutMethods: Array<{ id: CheckoutMethod; label: string }> = [
  { id: "balance", label: "Баланс ASTRACAT" }, { id: "yookassa", label: "ЮKassa" }, { id: "yoomoney", label: "ЮMoney" }, { id: "cryptopay", label: "Crypto Pay" }, { id: "heleket", label: "Heleket" }, { id: "lava", label: "LAVA" }, { id: "freekassa", label: "FreeKassa" }, { id: "overpay", label: "Overpay" }, { id: "platega", label: "Platega" },
];

function OrderModal({ token, tariffCategories, olcrtcCategories, initialProduct, close, reload, inform }: { token: string; tariffCategories: PublicTariffCategory[]; olcrtcCategories: WdttClientCategoryItem[]; initialProduct: CheckoutProduct; close: () => void; reload: () => Promise<void>; inform: (message: string) => void }) {
  const [step, setStep] = useState(1); const [product, setProduct] = useState<CheckoutProduct>(initialProduct); const [categoryId, setCategoryId] = useState(""); const [planId, setPlanId] = useState(""); const [method, setMethod] = useState<CheckoutMethod>("balance"); const [promoCode, setPromoCode] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const categories = product === "vpn" ? tariffCategories : olcrtcCategories;
  const category = categories.find((item) => item.id === categoryId);
  const plans = category?.tariffs ?? [];
  const plan = plans.find((item) => item.id === planId);
  const setProductAndReset = (value: CheckoutProduct) => { setProduct(value); setCategoryId(""); setPlanId(""); setStep(1); };
  const chooseCategory = (value: string) => { setCategoryId(value); setPlanId(""); };
  const execute = async () => {
    if (!plan) return; setBusy(true); setError(null);
    const payload = product === "vpn" ? { tariffId: plan.id, promoCode: promoCode.trim() || undefined } : { wdttTariffId: plan.id, promoCode: promoCode.trim() || undefined };
    try {
      if (method === "balance") { const result = await api.clientPayByBalance(token, payload); inform(result.message); await reload(); close(); return; }
      if (method === "yookassa") { const result = await api.yookassaCreatePayment(token, payload); window.location.assign(result.confirmationUrl); return; }
      if (method === "yoomoney") { const result = await api.yoomoneyCreateFormPayment(token, { ...payload, paymentType: "AC" }); window.location.assign(result.paymentUrl); return; }
      if (method === "cryptopay") { const result = await api.cryptopayCreatePayment(token, payload); window.location.assign(result.payUrl); return; }
      if (method === "heleket") { const result = await api.heleketCreatePayment(token, payload); window.location.assign(result.payUrl); return; }
      if (method === "lava") { const result = await api.lavaCreatePayment(token, payload); window.location.assign(result.payUrl); return; }
      if (method === "freekassa") { const result = await api.freekassaCreatePayment(token, payload); window.location.assign(result.payUrl); return; }
      if (method === "overpay") { const result = await api.overpayCreatePayment(token, payload); window.location.assign(result.payUrl); return; }
      const result = await api.clientCreatePlategaPayment(token, { ...payload, paymentMethod: 2 }); window.location.assign(result.paymentUrl);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось создать платёж"); } finally { setBusy(false); }
  };
  return <Modal title={product === "olcrtc" ? "Заказ OlcRTC" : "Заказ услуги"} onClose={close}><div className="ac-modal-body"><Stepper step={step} total={3} />{step === 1 && <section className="ac-form-grid"><FormField label="Продукт"><Select value={product} onChange={(event) => setProductAndReset(event.target.value as CheckoutProduct)}><option value="vpn">VPN-подписка</option><option value="olcrtc">OlcRTC</option></Select></FormField><FormField label="Категория"><Select value={categoryId} onChange={(event) => chooseCategory(event.target.value)}><option value="">Выберите категорию</option>{categories.map((item) => <option key={item.id} value={item.id}>{"emoji" in item && item.emoji ? `${item.emoji} ${item.name}` : item.name}</option>)}</Select></FormField><FormField label="Тариф"><Select value={planId} disabled={!categoryId} onChange={(event) => setPlanId(event.target.value)}><option value="">Выберите тариф</option>{plans.map((item) => <option key={item.id} value={item.id}>{item.name} — {money(item.price, item.currency)}</option>)}</Select></FormField></section>}{step === 2 && <section className="ac-form-grid"><section className="ac-order-summary"><span>{plan?.name}</span><span>{plan?.durationDays} дней</span><strong>{plan ? money(plan.price, plan.currency) : "—"}</strong></section><FormField label="Промокод"><Input placeholder="Необязательно" value={promoCode} onChange={(event) => setPromoCode(event.target.value.toUpperCase())} /></FormField><p className="ac-hint">Персональная скидка и промокод проверяются и рассчитываются на сервере при создании платежа.</p></section>}{step === 3 && <FormField label="Способ оплаты"><Select value={method} onChange={(event) => setMethod(event.target.value as CheckoutMethod)}>{checkoutMethods.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</Select></FormField>}{error && <p className="text-destructive">{error}</p>}<div className="ac-modal-actions"><Button tone="secondary" disabled={busy || step === 1} onClick={() => setStep((current) => current - 1)}>Назад</Button><Button disabled={busy || !planId} onClick={() => step < 3 ? setStep((current) => current + 1) : void execute()}>{step === 3 ? busy ? "Создаём платёж…" : "Перейти к оплате" : "Далее"}</Button></div></div></Modal>;
}
